name: seanallen
favicon: null
layout_spectrum: 0.13718291954137385
typography_spectrum: 0.395830768160522
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.8210347769781947
  lightness: 0.27371266670525074
  saturation: 0.2560911285690963
  rhythmicContrast: 0.346582870464772
purpose: []
